#--------------------------------------
# Github Action Part -1  -> Basics
#--------------------------------------

name: My-GitHubActions-Basics

on:
  push:
      branches:
         -master

 jobs:
    my_testing:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/chekout@v1
    - name: Run a one-line script
      run:
          echo Add other actions to build,
          echo test,and deploy your project
          
    
    my_deploy:
      runs-on: ubuntu-latest
      steps:
    
    
